package com.trade.bigone.dao.model;

import java.util.Date;

public class ActionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action
     *
     * @mbggenerated
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.id
     *
     * @return the value of action_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.id
     *
     * @param id the value for action_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.gmt_create
     *
     * @return the value of action_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.gmt_create
     *
     * @param gmtCreate the value for action_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.gmt_modified
     *
     * @return the value of action_log.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.gmt_modified
     *
     * @param gmtModified the value for action_log.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action
     *
     * @return the value of action_log.action
     *
     * @mbggenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action
     *
     * @param action the value for action_log.action
     *
     * @mbggenerated
     */
    public void setAction(String action) {
        this.action = action;
    }
}