package com.trade.bigone.dao.mapper;

import com.trade.bigone.dao.model.ActionLog;
import com.trade.bigone.dao.model.ActionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int countByExample(ActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int deleteByExample(ActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int insert(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int insertSelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    List<ActionLog> selectByExample(ActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    ActionLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActionLog record, @Param("example") ActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActionLog record, @Param("example") ActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActionLog record);
}